baseurl = "/"
languageCode = "en-us"
title = "John Svensson"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "â†©"
pygmentsCodeFences = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[params]
    description = ""
    footer = "Open Source | [GitHub](https://github.com/johndevman)"

